### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by HDembinski** [hliberacki/cpp-member-accessor#6] opened 2020-12-06 13:00 UTC
I use your library to implement serialization for classes in a legacy code base that I cannot (easily) change. I use the library to write to the private members.

I noticed a few things:
- It works great on Linux with gcc.
- It works on OSX with Apple Clang but only if I chose unique `accessor_name`s in different TUs that are linked together. If I chose the same `accessor_name` for different classes in different TUs, the program compiles fine, but at runtime the wrong specialization seems to be used, which means the member is accessed at the wrong memory location (leading to UB and segfaults).
- On Windows with msvc, I could not get it to work. I am getting `Windows fatal exception: access violation`

Did you test your code on Windows? I think you should set up CI jobs run the unit tests on all platforms. In theory, the solution should work everywhere, but in practice compilers tend to have bugs in corner cases such as this.

**Comment by hliberacki** [comment] 2020-12-07 13:17
Hi @HDembinski,

First of all, it's great to hear that the library is used :). Unfortunately, it's not tested properly since it was more like an R&D to check if I will be able to even ship it. 

Until today I did not have a direct signal that it's used by anyone - therefore I did not push any releases nor commits. But since it's used, you are definitely right I will enhance it and take a look at the problem on Windows. CI is definitely needed, then. 

I will get back to you as soon as I will reproduce it and make it work. Is it possible for you to give me the compiler version along with a simple dummy snippet that doesn't work for you? It would make it a little bit easier for me :)

**Comment by hliberacki** [comment] 2021-01-11 23:35
Hi @HDembinski,

Extremely sorry for the lack of my input, but I was very short on time lately. The latest pull request provided by @UladzislauRF is fixing this issue, and the code works perfectly fine for MSVC.

If you still need this change, you can freely compile it on your Windows setup. 

I am closing this issue

**Closed by hliberacki** 2021-01-11 23:35 UTC
